version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://train_user:train_pass@db:5432/train_control
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=train_control
      - POSTGRES_USER=train_user
      - POSTGRES_PASSWORD=train_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U train_user -d train_control"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
